/* Consulta para conferir lançamentos em aberto e créditos relacionados
   aos idlancamento identificados no JSON fornecido.

   Execute no banco Firebird com ISQL ou ferramenta equivalente.

   Ajuste os formatos de data/decimal conforme necessário.
*/

/* --- Lançamentos ainda em aberto + créditos associados --- */
WITH selected_lancamentos AS (
  SELECT 612 AS idlancamento FROM RDB$DATABASE UNION ALL
  SELECT 613 FROM RDB$DATABASE UNION ALL
  SELECT 619 FROM RDB$DATABASE UNION ALL
  SELECT 620 FROM RDB$DATABASE UNION ALL
  SELECT 614 FROM RDB$DATABASE UNION ALL
  SELECT 621 FROM RDB$DATABASE UNION ALL
  SELECT 8115 FROM RDB$DATABASE UNION ALL
  SELECT 8117 FROM RDB$DATABASE UNION ALL
  SELECT 615 FROM RDB$DATABASE UNION ALL
  SELECT 622 FROM RDB$DATABASE UNION ALL
  SELECT 8119 FROM RDB$DATABASE UNION ALL
  SELECT 623 FROM RDB$DATABASE UNION ALL
  SELECT 616 FROM RDB$DATABASE UNION ALL
  SELECT 8121 FROM RDB$DATABASE UNION ALL
  SELECT 624 FROM RDB$DATABASE UNION ALL
  SELECT 617 FROM RDB$DATABASE UNION ALL
  SELECT 625 FROM RDB$DATABASE UNION ALL
  SELECT 8123 FROM RDB$DATABASE UNION ALL
  SELECT 8125 FROM RDB$DATABASE UNION ALL
  SELECT 8127 FROM RDB$DATABASE UNION ALL
  SELECT 626 FROM RDB$DATABASE UNION ALL
  SELECT 627 FROM RDB$DATABASE UNION ALL
  SELECT 15571 FROM RDB$DATABASE UNION ALL
  SELECT 8128 FROM RDB$DATABASE UNION ALL
  SELECT 8129 FROM RDB$DATABASE UNION ALL
  SELECT 618 FROM RDB$DATABASE UNION ALL
  SELECT 8114 FROM RDB$DATABASE UNION ALL
  SELECT 15572 FROM RDB$DATABASE UNION ALL
  SELECT 8116 FROM RDB$DATABASE UNION ALL
  SELECT 15573 FROM RDB$DATABASE UNION ALL
  SELECT 8118 FROM RDB$DATABASE UNION ALL
  SELECT 15574 FROM RDB$DATABASE UNION ALL
  SELECT 15575 FROM RDB$DATABASE UNION ALL
  SELECT 19489 FROM RDB$DATABASE UNION ALL
  SELECT 8120 FROM RDB$DATABASE UNION ALL
  SELECT 8122 FROM RDB$DATABASE UNION ALL
  SELECT 8124 FROM RDB$DATABASE UNION ALL
  SELECT 19490 FROM RDB$DATABASE UNION ALL
  SELECT 8126 FROM RDB$DATABASE UNION ALL
  SELECT 19491 FROM RDB$DATABASE UNION ALL
  SELECT 22221 FROM RDB$DATABASE UNION ALL
  SELECT 23868 FROM RDB$DATABASE
),
em_aberto AS (
  SELECT
    fl.idlancamento,
    fl.dtvencimento,
    fl.vrliquido
  FROM fin_lancamentopr fl
  WHERE fl.idlancamento IN (SELECT idlancamento FROM selected_lancamentos)
    AND COALESCE(fl.isencerrado, 0) = 0
),
creditos AS (
  SELECT
    fm.idmovconta,
    fm.idlancamento,
    fm.dtmovimento,
    fm.valormovimento
  FROM fin_movconta fm
  WHERE fm.idlancamento IN (SELECT idlancamento FROM selected_lancamentos)
    AND COALESCE(fm.iscredito, 0) = 1
)
SELECT
  'EM ABERTO' AS origem,
  ea.idlancamento,
  ea.dtvencimento,
  ea.vrliquido AS valor
FROM em_aberto ea
UNION ALL
SELECT
  'CREDITO' AS origem,
  cr.idlancamento,
  cr.dtmovimento,
  cr.valormovimento
FROM creditos cr
ORDER BY 1, 2 DESC;
